networks:
    app_network:
        driver: bridge
services:
    nginx:
        image: 'jc21/nginx-proxy-manager:latest'
        container_name: 'nginx-proxy-manager'
        restart: always
        networks:
            - app_network
        ports:
            - '80:80'       # HTTP
            - '81:81'       # Admin interface
            - '443:443'     # HTTPS
        volumes:
            - ~/docker/data:/data
            - ~/docker/data/letsencrypt:/etc/letsencrypt

    phpmyadmin:
        image: 'phpmyadmin/phpmyadmin:latest'
        container_name: phpmyadmin
        restart: always
        networks:
            - app_network
        environment:
            PMA_HOST: database
        ports:
            - '8001:80'

    database:
        image: 'mariadb:latest'
        container_name: 'database'
        restart: always
        networks:
            - app_network
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
        volumes:
            - ~/docker/data/mysql:/var/lib/mysql

    icecast:
        image: 'pltnk/icecast2'
        container_name: icecast
        restart: always
        ports:
            - '1990:1990'
        networks:
            - app_network
        volumes:
            - ./icecast/icecast.xml:/etc/icecast2/icecast.xml

    backend:
        build:
            context: .
            dockerfile: ./docker/backend.Dockerfile
        container_name: backend
        restart: always
        networks:
            - app_network
        volumes:
            - ./:/var/www/html
        environment:
            - TZ=Asia/Tehran
        depends_on:
            - database
            - nginx
            - liquidsoap
            - icecast

    liquidsoap:
        build:
            context: .
            dockerfile: ./docker/liquidsoap.Dockerfile
        image: savonet/liquidsoap:v2.3.1
        container_name: liquidsoap
        volumes:
            - ./docker/liquidsoap/radio.liq:/radio.liq
        ports:
            - 127.0.0.1:9090:1234
        networks:
            - app_network
        command: [ "liquidsoap", "/radio.liq" ]
        environment:
            - TZ=Asia/Tehran
        restart: always
